name: Unity Windows Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'v*'

permissions: 
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build Unity project
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: StandaloneWindows64
          buildName: DragonWorm
          unityVersion: auto
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsBuild
          path: build

      - name: Debug build output
        run: |
            echo "Current directory:"
            pwd
            echo "Listing files:"
            ls -R

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: build/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
